# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1824103da06204bce64382ad7f108f957f0b11895b8dffd4b0350b2c226997c30fa6a5289ea876c9533baa246d0b3f6112b95165a450523dfc8c55331ba8c1d1

test:
  secret_key_base: ecdcc30cf1782887fde1fb184701eda64164edaf3f08a2d7604ee607dd3c0e0d28f42421615aeb875eda3aed52d660acee87a65031368d2dd27ec61f80671ab1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
